### PR TITLE
Added JSON parse if string is valid JSON

### PR DESCRIPTION
**Pull request by GustavoCaso**
#7 
@arturictus Added JSON parse.

I had some with the error handling, I didn't know if you prefer to fail with custom error from the gem or let the `JSON` error to propagate. Either way is really quick to change it.

Anything you want me to change just let me know.

I will continue with  this issue #8

### CODE REVIEW

**Comment by arturictus** [comment]
Hi @GustavoCaso,
I think this should be moved to an Adapter.
HashMap::JSONAdapter.call(string) if original.class <= String
with `<=` we check if String is and ancestor class.

And I think this should be done in Base not in Mapper
https://github.com/arturictus/hash_map/blob/master/lib/hash_map/base.rb

Thanks for the PR

**Comment by GustavoCaso** [comment]
@arturictus Great, I will apply the feedback.

Why you think is good to use the Adapter Pattern here ?

**Comment by arturictus** [comment]
Adapter is a good way to say: "this is not my expected input but I know somebody who can help me with it" 
And it separates the responsibilities of preparing the JSON to be ready for the mapper and the map it self.

**Comment by GustavoCaso** [comment]
Great I will improve the code

**Comment by GustavoCaso** [comment]
@arturictus I had added the `JSONAdapter` we have talked about

**Pull request merged**
